# use our self-build alpine base image installed with docker binary files, mvn, jdk8, kubectl and sonar-scanner binary
image: gitlab.wisers.com:2443/rnd-backend/lib/docker-maven-jdk8
# need to add this service if we want to use "docker info", "docker build" or "docker push"
services:
  - docker:18.09-dind
variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Xms1000m -Xmx1000m"

cache:
  paths:
    - .m2/repository/

before_script:
  - mkdir ~/.m2
  - echo $M2_SETTINGS > ~/.m2/settings.xml

stages:
  - spark-catalyst_2.11
  - spark-sql_2.11

spark-catalyst_2.11:
  stage: spark-catalyst_2.11
  when: manual
  tags:
    - backend
  variables:
    POM: sql/catalyst/pom.xml
  script:
    - mvn clean deploy -e -DskipTests -f ${POM} -T 30 -X
  only:
    - 2.4.3.1-kl

spark-sql_2.11:
  stage: spark-sql_2.11
  when: manual
  tags:
    - backend
  variables:
    POM: sql/core/pom.xml
  script:
    - mvn clean deploy -e -DskipTests -f ${POM} -T 30 -X
  only:
    - 2.4.3.1-kl
